apiVersion: v1
kind: Namespace
metadata:
  name: schnitzel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schnitzel
  namespace: schnitzel
spec:
  selector:
    matchLabels:
      app: schnitzel
  template:
    metadata:
      labels:
        app: schnitzel
    spec:
      containers:
      - name: schnitzel
        image: ghcr.io/michaelsp/schnitzel:0.1.0
        resources:
          limits:
            memory: '128Mi'
            cpu: '500m'
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: schnitzel
  namespace: schnitzel
spec:
  selector:
    app: schnitzel
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: 'true'
  name: schnitzel
  namespace: schnitzel
spec:
  tls:
  - hosts:
    - schnitzel.sprauer.net
    secretName: schnitzel-tls
  rules:
  - host: schnitzel.sprauer.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: schnitzel
            port:
              number: 3000
